### ISSUE TITLE
More to do?

### ISSUE THREAD

**Issue by seewoo5** [seewoo5/lean-poly-abc#19]
* [x] Fermat-Catalan
* [x] Nonparametrizablity of certain elliptic curve $y^2 = x^3 + x$ (and $y^2 = x^3 + 1$). The former case is in Lemmermeyer's note, and the latter case can be also proven by the similar method. I don't know yet how to deal with the general case (true when disciminant is nonzero) with Mason's theorem
* [x] Davenport's theorem: for nonconstant $f(t), g(t) \in k[t]$ with $f^3 - g^2 \ne 0$, we have $deg(f^3 - g^2) \ge \frac{1}{2} \deg(f) + 1$. Currently I'm working on this on `davenport` branch. (It seems that this was the original motivation for Mason-Stother's theorem)
* Analogue of Roth's theorem
* Analogue of effective Mordell

**Comment by jcpaik** [comment]
Fermat-Catalan done in #20

**Comment by seewoo5** [comment]
- [ ] Davenport's theorem: for nonconstant $f(t), g(t) \in k[t]$ with $f^3 - g^2 \ne 0$, we have $deg(f^3 - g^2) \ge \frac{1}{2} \deg(f) + 1$. Currently I'm working on this on `davenport` branch.

**Comment by seewoo5** [comment]
Davenport done in #24
