### ISSUE TITLE
Pain Points

### ISSUE THREAD

**Issue by seewoo5** [seewoo5/lean-poly-abc#3]
* algebraic closure: https://leanprover-community.github.io/mathlib_docs/field_theory/is_alg_closed/algebraic_closure.html#algebraic_closure
* polynomial roots: `polynomial.roots`, `polynomial.root_set`
* Maybe we don't need to define actual radical of a polynomial, but only the number of roots.

**Comment by jcpaik** [comment]
It's hard to show that the `num` and `denom` of a `ratfunc` are coprime. 

Simply trying to rewrite the definition does not work. It results in full gibberish.
```
theorem is_coprime.num_denom (x : ratfunc k) : is_coprime x.num x.denom :=
begin
  rw [ratfunc.num, ratfunc.denom],
  simp_rw [ratfunc.num_denom],
end
```

The idea is to mix three things. [ratfunc.denom_div](https://leanprover-community.github.io/mathlib_docs/field_theory/ratfunc.html#ratfunc.denom_div) and [ratfunc.mk_eq_div](https://leanprover-community.github.io/mathlib_docs/field_theory/ratfunc.html#ratfunc.mk_eq_div) and [ratfunc.induction_on](https://leanprover-community.github.io/mathlib_docs/field_theory/ratfunc.html#ratfunc.induction_on). This is not all all trivial for anyone who is reading this for the first time.

**Comment by seewoo5** [comment]
In Stothers' paper, there's a slightly different version of ABC for not necessarily coprime polynomials (Theorem 1.2). Following the proof, it can be translated as follows: for zero-sum distinct triple of nonzero polynomials $a, b, c \in k[t]$, $a + b + c = 0$ implies $\max\{\deg(a), \deg(b), \deg(c) \} + 1 \le \deg(\rad(a)) + \deg(\rad(b)) + \deg(c)$ (the $\deg(\rad(c))$ of RHS of the original ABC inequality is replaced by $\deg(c)$. Using this, we can remove the coprimality hypothesis for Davenport's theorem (but not sure about the positive characteristic case).

**Comment by jcpaik** [comment]
@seewoo5 I think we need to work on this slightly different version of ABC for non-coprime polynomials
