### ISSUE TITLE
Porting `Wronskian.lean`

### ISSUE THREAD

**Issue by jcpaik** [seewoo5/lean-poly-abc#46]
- [x] Find the most general scalar ring/field `k`

My impression is that a PID scalar ring could be enough.

**Comment by seewoo5** [comment]
Wronskian can be defined for "any" ring (maybe commutative, ...) with derivation $D: R \to R$ (see [`RingTheory/Derivation/Basic.lean`](https://github.com/leanprover-community/mathlib4/blob/dfc07f1b6271219de25170e4936fee9443d4234c/Mathlib/RingTheory/Derivation/Basic.lean#L44)), but for now, let's generalize it to polynomial ring but with more general coefficient ring (e.g. `CommRing` or even `SemiRing`)

**Comment by seewoo5** [comment]
https://github.com/leanprover-community/mathlib4/pull/14243

**Comment by seewoo5** [comment]
Related mathlib4 PRs:

* https://github.com/leanprover-community/mathlib4/pull/14281
* https://github.com/leanprover-community/mathlib4/pull/14243
